# Generated by Django 3.2.4 on 2021-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel_data_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='loogin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='carousel_data',
            name='name',
            field=models.CharField(default='Undefined', max_length=50),
        ),
    ]
