# Generated by Django 3.2.4 on 2021-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210907_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loogin_data',
            name='email',
        ),
    ]
