# Generated by Django 3.2.4 on 2021-09-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_loogin_data_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loogin_data',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
    ]
