# Generated by Django 3.2.4 on 2021-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_loogin_data_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('project_image', models.ImageField(default='', upload_to='home/images')),
                ('project_descp', models.CharField(max_length=100)),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
    ]
